# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Consultor√≠a SEO"
  pageRef = "consultoria-seo"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "Acerca de"
  pageRef = "acerca-de"
  weight = 30

[[main]]
  name = "Contacto"
  url = "https://tidycal.com/spelucin/seo-exploracion-30-min"
  weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
   name = "Etiquetas"
   pageRef = "tags"
   weight = 10

[[footer]]
   name = "Privacidad"
   pageRef = "privacidad"
   weight = 20

[[footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/spelucin/"
  weight = 30
  [footer.params]
    icon = "linkedin"
    showName = false
    target = "_blank"

[[footer]]
  name = "GitHub"
  url = "https://github.com/spelucin/"
  weight = 40
  [footer.params]
    icon = "github"
    showName = false
    target = "_blank"

[[footer]]
  name = "Mastodon"
  url = "https://mstdn.social/@spelucin"
  weight = 50
  [footer.params]
    icon = "mastodon"
    showName = false
    target = "_blank"
